name: Flutter Test
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"

jobs:
  flutter_test:
    name: Run flutter test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage/lcov.info
